version: '3.8'

services:
  db:
    container_name: blogs_api_db
    image: mysql:8.0.23
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogs_api
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 5s

  api:
    image: node:16.14
    container_name: blogs_api
    tty: true
    stdin_open: true
    command: bash -c "chgrp -R node /root && chown -R node /root && npm install && npm run drop && npm run prestart && npm run seed && npm run debug"
    restart: on-failure
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DATABASE: blogs_api
      JWT_SECRET: secretJWT
      API_HOST: localhost
      API_PORT: 3001
      NODE_ENV: 'development'
